/*단답형
2P
1. 논리 설계
2. 데이터 모델링
3P
1.E-R모델
2.E-R모델
3.Entity

4p
1. E-R Diagram
2. 관계

5p
1.카디널리티
2.옵셔널리티

6p
1. 스키마
2. 테이블

7p
1.Table
2.Index
3.Sequence*/


--실습과제 P1
SELECT EMPNO AS "EMPLOYEE_NO"
	, ENAME  AS "EMPLOYEE_NAME"
	, JOB
	, MGR AS "MANAGER"
	, HIREDATE
	, SAL AS "SALARY"
	, COMM AS "COMMISSION"
	, DEPTNO AS "DEPARTMENT_NO" 
 FROM EMP
 ORDER BY DEPTNO DESC, ENAME ASC;


--실습과제 P2 1번
SELECT *
 FROM EMP 
 WHERE COMM IS NULL
   AND SAL > NULL;
--NULL 비교연산 시 FALSE.. 값 출력되는 거 없음. 문제 출제 의도가 이게 맞나용...?
 

-- 실습과제 P2 2번
SELECT *
 FROM EMP 
 WHERE MGR IS NULL
  AND COMM IS NULL;

 
--실습과제 P3 1번
SELECT *FROM EMP
 WHERE ENAME LIKE '%S';
 
--실습과제 P3 2번
 SELECT *
  FROM EMP 
  WHERE JOB = 'SALESMAN'
    AND DEPTNO = 30;
 
--실습과제 P3 3번
 SELECT *
  FROM EMP 
  WHERE DEPTNO IN (20,30)
    AND SAL > 2000;
 
--실습과제 P3 4번 
 SELECT *
  FROM EMP 
  WHERE DEPTNO = 20
    AND SAL > 2000
  
 UNION 
  
 SELECT *
  FROM EMP
  WHERE DEPTNO = 30
    AND SAL > 2000;
 
--실습과제 P3 5번

SELECT *
 FROM EMP
 WHERE COMM IS NULL
 	AND MGR IS NOT NULL
 	AND JOB IN ('MANAGER','CLERK')
 	AND ENAME NOT LIKE '_L%';


--실습과제 P4 1번

SELECT EMPNO, ENAME, SUBSTR(TO_CHAR(EMPNO),1,2)||'**' AS EMPNO마스킹처리,
SUBSTR(ENAME,1,1)||'*****' AS ENAME마스킹처리
 FROM EMP
 WHERE LENGTH(ENAME)>=6 ;


--실습과제 P4 2번
SELECT EMPNO, ENAME, JOB, SAL, SAL/20 AS DAY_PER_SAL, SAL/20/8 AS HOUR_PER_SAL
 FROM EMP
 WHERE JOB IN ('SALESMAN', 'CLERK')
 ORDER BY SAL ASC;


--실습과제 P5 3번

SELECT EMPNO, ENAME, TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'), 'YYYY-MM-DD') AS HIREDATE,
 DECODE (COMM, NULL, 'N/A', COMM) 
 FROM EMP;


--실습과제 P5 4번
SELECT EMPNO, ENAME, MGR,
 (CASE WHEN MGR IS NULL THEN '0000'
 WHEN SUBSTR(MGR,1,2)='75' THEN '5555'
 WHEN SUBSTR(MGR,1,2)='76' THEN '6666'
 WHEN SUBSTR(MGR,1,2)='77' THEN '7777'
 WHEN SUBSTR(MGR,1,2)='78' THEN '8888'
 ELSE '9999' END) AS CHG_MGR
 FROM EMP ;



